version: '3.4'

services:
  chyll-server:
    image: jamiegyoung22/chyll-server:latest
    build:
      context: server
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 3000:3000
      - 9229:9229
    env_file: ./server/.env
    command: ["node", "--inspect=0.0.0.0:9229", "index.js"]
